In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_excel("/content/drive/MyDrive/Bert/hello.xlsx")

In [4]:
data

Release_Number    Label              Date  \
0              97.0      New  February 8, 2022   
1              97.0    Fixed  February 8, 2022   
2              97.0    Fixed  February 8, 2022   
3              97.0  Changed  February 8, 2022   
4              97.0  Changed  February 8, 2022   
...             ...      ...               ...   
1328         37.0.1    Fixed     April 3, 2015   
1329         37.0.1  Changed     April 3, 2015   
1330         37.0.2    Fixed    April 20, 2015   
1331         37.0.2    Fixed    April 20, 2015   
1332         37.0.2    Fixed    April 20, 2015   

                                           Release_Note  
0     Firefox now supports and displays the new styl...  
1     On macOS, we’ve made improvements to system fo...  
2                               Various security fixes   
3     On February 8, we will be expiring the 18 colo...  
4     Support for directly generating PostScript for...  
...                                                 ...  
1328             \n    Various security fixes\n    \n    
1329             \n    Disabled HTTP/2 AltSvc\n    \n    
1330  \n    Google Maps may render incorrectly in so...  
1331  \n    Stability fixes for select graphics hard...  
1332             \n    Various security fixes\n    \n    

[1333 rows x 4 columns]

In [5]:
data["Label"].unique()

array(['New', 'Fixed', 'Changed'], dtype=object)

In [8]:
data["Release_Note"][151].strip()

'PDF forms now support JavaScript embedded in PDF files. Some PDF forms use JavaScript for validation and other interactive features.'

In [10]:
for j in range(1333):
    metin = data["Release_Note"][j].strip()
    data["Release_Note"][j]=metin


In [11]:
data

Release_Number    Label              Date  \
0              97.0      New  February 8, 2022   
1              97.0    Fixed  February 8, 2022   
2              97.0    Fixed  February 8, 2022   
3              97.0  Changed  February 8, 2022   
4              97.0  Changed  February 8, 2022   
...             ...      ...               ...   
1328         37.0.1    Fixed     April 3, 2015   
1329         37.0.1  Changed     April 3, 2015   
1330         37.0.2    Fixed    April 20, 2015   
1331         37.0.2    Fixed    April 20, 2015   
1332         37.0.2    Fixed    April 20, 2015   

                                           Release_Note  
0     Firefox now supports and displays the new styl...  
1     On macOS, we’ve made improvements to system fo...  
2                                Various security fixes  
3     On February 8, we will be expiring the 18 colo...  
4     Support for directly generating PostScript for...  
...                                                 ...  
1328                             Various security fixes  
1329                             Disabled HTTP/2 AltSvc  
1330   Google Maps may render incorrectly in some cases  
1331  Stability fixes for select graphics hardware a...  
1332                             Various security fixes  

[1333 rows x 4 columns]

In [12]:
data["Release_Note"][1328]

'Various security fixes'

In [14]:
data['labels'] = pd.factorize(data.Label)[0]

In [15]:
data

Release_Number    Label              Date  \
0              97.0      New  February 8, 2022   
1              97.0    Fixed  February 8, 2022   
2              97.0    Fixed  February 8, 2022   
3              97.0  Changed  February 8, 2022   
4              97.0  Changed  February 8, 2022   
...             ...      ...               ...   
1328         37.0.1    Fixed     April 3, 2015   
1329         37.0.1  Changed     April 3, 2015   
1330         37.0.2    Fixed    April 20, 2015   
1331         37.0.2    Fixed    April 20, 2015   
1332         37.0.2    Fixed    April 20, 2015   

                                           Release_Note  labels  
0     Firefox now supports and displays the new styl...       0  
1     On macOS, we’ve made improvements to system fo...       1  
2                                Various security fixes       1  
3     On February 8, we will be expiring the 18 colo...       2  
4     Support for directly generating PostScript for...       2  
...                                                 ...     ...  
1328                             Various security fixes       1  
1329                             Disabled HTTP/2 AltSvc       2  
1330   Google Maps may render incorrectly in some cases       1  
1331  Stability fixes for select graphics hardware a...       1  
1332                             Various security fixes       1  

[1333 rows x 5 columns]

In [16]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(data, test_size=0.2, random_state=42)

In [17]:
train=train[["Release_Note","labels"]]
test=test[["Release_Note","labels"]]

In [18]:
!pip install simpletransformers

     |████████████████████████████████| 249 kB 9.8 MB/s 
     |████████████████████████████████| 6.6 MB 47.5 MB/s 
     |████████████████████████████████| 1.8 MB 36.7 MB/s 
     |████████████████████████████████| 1.2 MB 47.2 MB/s 
     |████████████████████████████████| 4.0 MB 45.9 MB/s 
     |████████████████████████████████| 342 kB 51.7 MB/s 
     |████████████████████████████████| 10.1 MB 40.9 MB/s 
     |████████████████████████████████| 43 kB 2.2 MB/s 
     |████████████████████████████████| 84 kB 3.7 MB/s 
     |████████████████████████████████| 880 kB 50.5 MB/s 
     |████████████████████████████████| 596 kB 45.9 MB/s 
     |████████████████████████████████| 145 kB 52.8 MB/s 
     |████████████████████████████████| 181 kB 55.8 MB/s 
     |████████████████████████████████| 63 kB 1.6 MB/s 
     |████████████████████████████████| 1.1 MB 47.4 MB/s 
     |████████████████████████████████| 136 kB 57.9 MB/s 
     |████████████████████████████████| 212 kB 51.0 MB/s 
     |██████████████

In [19]:
from simpletransformers.classification import ClassificationModel

In [20]:
train["Release_Note"]=train["Release_Note"].apply(lambda r: str(r))
train['labels']=train['labels'].astype(int)

In [21]:
model = ClassificationModel('bert', 'bert-base-uncased', num_labels=5, use_cuda=False,
                            args={'reprocess_input_data': True, 'overwrite_output_dir': True, 'num_train_epochs': 10, "train_batch_size": 64 , "fp16":False, "output_dir": "./drive/MyDrive/Bert/bert_model3"})

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/420M [00:00<?, ?B/s]

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.decoder.weight', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

In [22]:
model.train_model(train)

/usr/local/lib/python3.7/dist-packages/simpletransformers/classification/classification_model.py:586: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


  0%|          | 0/1066 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Running Epoch 0 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 1 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 2 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 3 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 4 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 5 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 6 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 7 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 8 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 9 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

(170, 0.3633248281610363)

In [23]:
result, model_outputs, wrong_predictions = model.eval_model(test)

/usr/local/lib/python3.7/dist-packages/simpletransformers/classification/classification_model.py:1427: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


  0%|          | 0/267 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/34 [00:00<?, ?it/s]

In [34]:
predictions = model_outputs.argmax(axis=1)

In [35]:
actuals = test.labels.values


In [36]:
predictions[:]

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 1, 0, 0, 2, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 2, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 2, 0, 1, 1, 2,
       0, 2, 0, 2, 1, 1, 2, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 2, 1, 1,
       1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 2, 2, 1, 1, 0, 2, 1, 0, 0, 1, 0, 2, 2, 0, 1, 0, 1,
       1, 0, 0, 2, 0, 1, 1, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 2, 1, 1, 0, 2, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 2, 1, 1, 0, 0, 2, 0, 2, 0, 1, 2, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 2, 1,
       0, 2, 0])

In [37]:
actuals[:]

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 2,
       1, 1, 0, 1, 2, 1, 1, 0, 1, 2, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1,
       2, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 1, 0, 1, 2, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 1, 2,
       0, 2, 0, 2, 1, 1, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 0, 2, 2, 2, 1, 1,
       1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1,
       1, 0, 1, 1, 0, 2, 2, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 2, 0, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 2, 1, 1, 2, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 2, 2, 1, 1, 0, 2, 2, 0, 2, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

In [38]:
actual = np.array(actuals[:])
predict = np.array(predictions[:])

In [39]:
from sklearn.metrics import accuracy_score
accuracy_score(actuals, predictions)

0.8389513108614233

In [40]:
import sklearn.metrics as mt
mt.confusion_matrix(actuals, predictions)

array([[ 96,   2,  11],
       [  5, 111,   3],
       [ 20,   2,  17]])

In [41]:
print(mt.classification_report(actual, predict))

              precision    recall  f1-score   support

           0       0.79      0.88      0.83       109
           1       0.97      0.93      0.95       119
           2       0.55      0.44      0.49        39

    accuracy                           0.84       267
   macro avg       0.77      0.75      0.76       267
weighted avg       0.83      0.84      0.83       267



In [42]:
örnek = test.iloc[65]['Release_Note']
print(örnek)

When entering a hostname (like pinterest.com) in the URL bar, Firefox resolves to the secure version of the site (https://www.pinterest.com) instead of the insecure version (http://www.pinterest.com) when possible


In [43]:
tahmin=model.predict([örnek])

if tahmin[0] ==0:
  print("new")
elif tahmin[0]==1:
  print("fixed")
elif tahmin[0]==2:
  print("changed")
elif tahmin[0]==3:
  print("other")
else:
  print("unresolved")

  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

new
