In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_excel("/content/drive/MyDrive/Bert/hello.xlsx")

In [4]:
data.head()

Release_Number    Label              Date  \
0           97.0      New  February 8, 2022   
1           97.0    Fixed  February 8, 2022   
2           97.0    Fixed  February 8, 2022   
3           97.0  Changed  February 8, 2022   
4           97.0  Changed  February 8, 2022   

                                        Release_Note  
0  Firefox now supports and displays the new styl...  
1  On macOS, we’ve made improvements to system fo...  
2                            Various security fixes   
3  On February 8, we will be expiring the 18 colo...  
4  Support for directly generating PostScript for...

In [5]:
data["Label"].unique()

array(['New', 'Fixed', 'Changed'], dtype=object)

In [6]:
data['labels'] = pd.factorize(data.Label)[0]

In [7]:
data.head()

Release_Number    Label              Date  \
0           97.0      New  February 8, 2022   
1           97.0    Fixed  February 8, 2022   
2           97.0    Fixed  February 8, 2022   
3           97.0  Changed  February 8, 2022   
4           97.0  Changed  February 8, 2022   

                                        Release_Note  labels  
0  Firefox now supports and displays the new styl...       0  
1  On macOS, we’ve made improvements to system fo...       1  
2                            Various security fixes        1  
3  On February 8, we will be expiring the 18 colo...       2  
4  Support for directly generating PostScript for...       2

In [8]:
!pip install simpletransformers

     |████████████████████████████████| 249 kB 32.4 MB/s 
     |████████████████████████████████| 342 kB 75.7 MB/s 
     |████████████████████████████████| 43 kB 2.7 MB/s 
     |████████████████████████████████| 6.6 MB 63.8 MB/s 
     |████████████████████████████████| 1.8 MB 56.1 MB/s 
     |████████████████████████████████| 10.1 MB 65.9 MB/s 
     |████████████████████████████████| 4.2 MB 61.0 MB/s 
     |████████████████████████████████| 1.2 MB 55.7 MB/s 
     |████████████████████████████████| 596 kB 60.2 MB/s 
     |████████████████████████████████| 84 kB 4.0 MB/s 
     |████████████████████████████████| 181 kB 80.8 MB/s 
     |████████████████████████████████| 145 kB 58.2 MB/s 
     |████████████████████████████████| 63 kB 1.4 MB/s 
     |████████████████████████████████| 136 kB 78.5 MB/s 
     |████████████████████████████████| 1.1 MB 64.2 MB/s 
     |████████████████████████████████| 212 kB 79.4 MB/s 
     |████████████████████████████████| 127 kB 78.8 MB/s 
     |█████████████

In [9]:
from simpletransformers.classification import ClassificationModel

In [10]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(data, test_size=0.2, random_state=42)

In [11]:
train=train[["Release_Note","labels"]]
test=test[["Release_Note","labels"]]

In [12]:
train["Release_Note"]=train["Release_Note"].apply(lambda r: str(r))
train['labels']=train['labels'].astype(int)

In [13]:
train["Release_Note"].head()

1280    \n    Keep track of articles and videos with P...
1110    \n    Add-on signing certificate expiration (B...
966     \n    Use Nirmala UI as fallback font for addi...
598     \n    Enabled AV1 support on 32-bit Windows an...
170     Video controls now have visible focus styling ...
Name: Release_Note, dtype: object

In [14]:
train["labels"].head()

1280    0
1110    1
966     1
598     0
170     1
Name: labels, dtype: int64

In [15]:
model = ClassificationModel('bert', 'distilbert-base-uncased',
                            num_labels=5, use_cuda=False,
                            args={'reprocess_input_data': True, 'overwrite_output_dir': True, 
                                  'num_train_epochs': 10, 
                                    "train_batch_size": 64 , "fp16":False, 
                                     "output_dir": "./drive/MyDrive/Bert/bert_model5"})

Downloading:   0%|          | 0.00/483 [00:00<?, ?B/s]

You are using a model of type distilbert to instantiate a model of type bert. This is not supported for all configurations of models and can yield errors.


Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing BertForSequenceClassification: ['distilbert.transformer.layer.5.sa_layer_norm.bias', 'distilbert.transformer.layer.5.ffn.lin2.weight', 'distilbert.transformer.layer.3.attention.v_lin.bias', 'distilbert.embeddings.LayerNorm.weight', 'distilbert.transformer.layer.1.ffn.lin2.bias', 'distilbert.transformer.layer.2.ffn.lin2.weight', 'distilbert.transformer.layer.4.attention.k_lin.bias', 'distilbert.embeddings.word_embeddings.weight', 'distilbert.transformer.layer.2.attention.k_lin.weight', 'distilbert.embeddings.LayerNorm.bias', 'distilbert.transformer.layer.0.ffn.lin2.bias', 'distilbert.transformer.layer.5.output_layer_norm.weight', 'distilbert.transformer.layer.5.attention.out_lin.bias', 'distilbert.transformer.layer.4.attention.out_lin.weight', 'distilbert.transformer.layer.5.attention.k_lin.bias', 'distilbert.transformer.layer.5.output_layer_norm.bias', 'distilbert.transformer.layer.0.output_

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/455k [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'DistilBertTokenizer'. 
The class this function is called from is 'BertTokenizerFast'.


In [16]:
model.train_model(train)

/usr/local/lib/python3.7/dist-packages/simpletransformers/classification/classification_model.py:586: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


  0%|          | 0/1066 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/transformers/optimization.py:309: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  FutureWarning,


Epoch:   0%|          | 0/10 [00:00<?, ?it/s]

Running Epoch 0 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 1 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 2 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 3 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 4 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 5 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 6 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 7 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 8 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

Running Epoch 9 of 10:   0%|          | 0/17 [00:00<?, ?it/s]

(170, 0.5958360190777218)

In [17]:
result, model_outputs, wrong_predictions = model.eval_model(test)

/usr/local/lib/python3.7/dist-packages/simpletransformers/classification/classification_model.py:1427: UserWarning: Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels.
  "Dataframe headers not specified. Falling back to using column 0 as text and column 1 as labels."


  0%|          | 0/267 [00:00<?, ?it/s]

Running Evaluation:   0%|          | 0/34 [00:00<?, ?it/s]

In [18]:
predictions = model_outputs.argmax(axis=1)

In [19]:
actuals = test.labels.values


In [20]:
predictions[:]

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 2, 2, 0, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 2, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 2, 0, 1, 1, 0, 1, 2, 0, 0, 0, 1, 1, 2, 1, 0, 0,
       0, 2, 1, 1, 0, 0, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 2, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 1, 2, 1, 1, 1, 1, 0, 1, 2, 1, 0, 1, 0, 2, 0, 0, 1,
       0, 1, 2, 1, 2, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 2, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 2, 0, 1, 1, 0, 2, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 2, 0, 2, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 2, 0, 2, 1, 0, 1, 0,
       2, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 2, 1, 0, 1, 1, 2, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0, 1, 2, 1, 1, 0, 2, 1, 1, 0,
       1, 1, 2, 0, 0, 0, 0, 1, 0, 2, 0, 1, 2, 2, 0, 1, 2, 0, 0, 1, 2, 1,
       0, 2, 1])

In [21]:
actuals[:]

array([1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 2,
       1, 1, 0, 1, 2, 1, 1, 0, 1, 2, 0, 1, 0, 2, 2, 0, 0, 0, 0, 0, 0, 1,
       2, 2, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 2, 2, 0, 0, 1, 1, 0, 1, 2, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 2, 0, 1, 1, 2,
       0, 2, 0, 2, 1, 1, 0, 2, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 1, 2, 0, 1, 0, 1, 0, 1, 1, 1, 0, 2, 2, 2, 1, 1,
       1, 2, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 2, 1, 1, 1,
       1, 0, 1, 1, 0, 2, 2, 1, 1, 0, 2, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 2, 0, 2, 2, 1, 1, 1, 2, 1, 2, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 2, 1, 2, 1, 1, 2, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 2, 2, 1, 1, 0, 2, 2, 0, 2, 0, 1, 1, 1, 1, 0, 2, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0])

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(actuals, predictions)

0.7528089887640449

In [23]:
actual = np.array(actuals[:])
predict = np.array(predictions[:])

In [24]:
import sklearn.metrics as mt
mt.confusion_matrix(actuals, predictions)

array([[ 84,   6,  19],
       [  3, 109,   7],
       [ 25,   6,   8]])

In [25]:
print(mt.classification_report(actual, predict))

              precision    recall  f1-score   support

           0       0.75      0.77      0.76       109
           1       0.90      0.92      0.91       119
           2       0.24      0.21      0.22        39

    accuracy                           0.75       267
   macro avg       0.63      0.63      0.63       267
weighted avg       0.74      0.75      0.75       267



In [26]:
örnek = test.iloc[21]['Release_Note']
print(örnek)


    To support unicode-range descriptor for webfonts, font matching under Linux now uses the same font matching code as other platforms
    
  


In [28]:
tahmin=model.predict([örnek])
if tahmin[0] ==0:
  print("new")
elif tahmin[0]==1:
  print("fixed")
elif tahmin[0]==2:
  print("changed")
elif tahmin[0]==3:
  print("other")
else:
  print("unresolved")


  0%|          | 0/1 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

new
